version: '3.7'

services:
  mongo:
    image: mongo:latest
    restart: "always"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    labels:
      - "com.example.description=mongdb Nasa Exoplanets DB"
      - "com.example.department=digitai"
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
